export const countries: string[] = [
    'Afghan',
    'Albanien',
    'Algérien',
    'Andorran',
    'Angolais',
    'Antiguais et Barbudien',
    'Argentin',
    'Arménien',
    'Australien',
    'Autrichien',
    'Azerbaïdjanais',
    'Bahaméen',
    'Bahreïni',
    'Bangladais',
    'Barbadien',
    'Biélorusse',
    'Belge',
    'Bélizien',
    'Béninois',
    'Bhoutanais',
    'Bolivien',
    'Bosnien ou Herzégovinien',
    'Botswanais',
    'Brésilien',
    'Britannique',
    'Brunéien',
    'Bulgare',
    'Burkinabé',
    'Birman',
    'Burundais',
    'Cap-verdien',
    'Cambodgien',
    'Camerounais',
    'Canadien',
    'Centrafricain',
    'Tchadien',
    'Chilien',
    'Chinois',
    'Colombien',
    'Comorien',
    'Congolais',
    'Costaricien',
    'Croate',
    'Cubain',
    'Chypriote',
    'Tchèque',
    'Danois',
    'Djiboutien',
    'Dominicain',
    'Timorais de l’Est',
    'Équatorien',
    'Égyptien',
    'Émirien',
    'Guinéen équatorial',
    'Érythréen',
    'Estonien',
    'Eswatinien',
    'Éthiopien',
    'Fidjien',
    'Finlandais',
    'Français',
    'Gabonais',
    'Gambien',
    'Géorgien',
    'Allemand',
    'Ghanéen',
    'Grec',
    'Grenadien',
    'Guatémaltèque',
    'Bissaoguinéen',
    'Guinéen',
    'Guyanien',
    'Haïtien',
    'Hondurien',
    'Hongrois',
    'I-Kiribatien',
    'Islandais',
    'Indien',
    'Indonésien',
    'Iranien',
    'Irakien',
    'Irlandais',
    'Israélien',
    'Italien',
    'Ivoirien',
    'Jamaïcain',
    'Japonais',
    'Jordanien',
    'Kazakhstanois',
    'Kényan',
    'Kitticien et Névisien',
    'Koweïtien',
    'Kirghize',
    'Laotien',
    'Lettone',
    'Libanais',
    'Libérien',
    'Libyen',
    'Liechtensteinois',
    'Lituanien',
    'Luxembourgeois',
    'Malgache',
    'Malawite',
    'Malaisien',
    'Maldivien',
    'Malien',
    'Maltais',
    'Marshallais',
    'Mauritanien',
    'Mauricien',
    'Mexicain',
    'Micronésien',
    'Moldave',
    'Monégasque',
    'Mongol',
    'Monténégrin',
    'Marocain',
    'Mosotho',
    'Motswana',
    'Mozambicain',
    'Namibien',
    'Nauruan',
    'Népalais',
    'Néo-Zélandais',
    'Nicaraguayen',
    'Nigérian',
    'Nigérien',
    'Nord-Coréen',
    'Macédonien du Nord',
    'Nord-Irlandais',
    'Norvégien',
    'Omanais',
    'Pakistanais',
    'Palaosien',
    'Palestinien',
    'Panaméen',
    'Papouasien-Néo-Guinéen',
    'Paraguayen',
    'Péruvien',
    'Polonais',
    'Portugais',
    'Qatarien',
    'Roumain',
    'Russe',
    'Rwandais',
    'Saint-Lucien',
    'Salvadorien',
    'Samoan',
    'Saint-Marinais',
    'Santoméen',
    'Saoudien',
    'Écossais',
    'Sénégalais',
    'Serbe',
    'Seychellois',
    'Sierra-léonais',
    'Singapourien',
    'Slovaque',
    'Slovène',
    'Îles Salomonais',
    'Somalien',
    'Sud-Africain',
    'Sud-Coréen',
    'Soudanais du Sud',
    'Espagnol',
    'Sri Lankais',
    'Soudanais',
    'Surinamien',
    'Swazi',
    'Suédois',
    'Suisse',
    'Syrien',
    'Taïwanais',
    'Tadjik',
    'Tanzanien',
    'Thaïlandais',
    'Togolais',
    'Tonguien',
    'Trinidadien ou Tobagonien',
    'Tunisienne',
    'Turc',
    'Tuvaluan',
    'Ougandais',
    'Ukrainien',
    'Uruguayen',
    'Ouzbek',
    'Vénézuélien',
    'Vietnamien',
    'Gallois',
    'Yéménite',
    'Zambien',
    'Zimbabwéen',
];
export const countryCodes: { code: string, name: string, flag: string }[] = [
    { code: '+93', name: 'Afghanistan', flag: '🇦🇫' },
    { code: '+355', name: 'Albanie', flag: '🇦🇱' },
    { code: '+213', name: 'Algérie', flag: '🇩🇿' },
    { code: '+376', name: 'Andorre', flag: '🇦🇩' },
    { code: '+244', name: 'Angola', flag: '🇦🇴' },
    { code: '+1268', name: 'Antigua-et-Barbuda', flag: '🇦🇬' },
    { code: '+54', name: 'Argentine', flag: '🇦🇷' },
    { code: '+374', name: 'Arménie', flag: '🇦🇲' },
    { code: '+61', name: 'Australie', flag: '🇦🇺' },
    { code: '+43', name: 'Autriche', flag: '🇦🇹' },
    { code: '+994', name: 'Azerbaïdjan', flag: '🇦🇿' },
    { code: '+1242', name: 'Bahamas', flag: '🇧🇸' },
    { code: '+973', name: 'Bahreïn', flag: '🇧🇭' },
    { code: '+880', name: 'Bangladesh', flag: '🇧🇩' },
    { code: '+1246', name: 'Barbade', flag: '🇧🇧' },
    { code: '+375', name: 'Biélorussie', flag: '🇧🇾' },
    { code: '+32', name: 'Belgique', flag: '🇧🇪' },
    { code: '+501', name: 'Belize', flag: '🇧🇿' },
    { code: '+229', name: 'Bénin', flag: '🇧🇯' },
    { code: '+975', name: 'Bhoutan', flag: '🇧🇹' },
    { code: '+591', name: 'Bolivie', flag: '🇧🇴' },
    { code: '+387', name: 'Bosnie-Herzégovine', flag: '🇧🇦' },
    { code: '+267', name: 'Botswana', flag: '🇧🇼' },
    { code: '+55', name: 'Brésil', flag: '🇧🇷' },
    { code: '+44', name: 'Royaume-Uni', flag: '🇬🇧' },
    { code: '+673', name: 'Brunéi', flag: '🇧🇳' },
    { code: '+359', name: 'Bulgarie', flag: '🇧🇬' },
    { code: '+226', name: 'Burkina Faso', flag: '🇧🇫' },
    { code: '+95', name: 'Birmanie', flag: '🇲🇲' },
    { code: '+257', name: 'Burundi', flag: '🇧🇮' },
    { code: '+238', name: 'Cap-Vert', flag: '🇨🇻' },
    { code: '+855', name: 'Cambodge', flag: '🇰🇭' },
    { code: '+237', name: 'Cameroun', flag: '🇨🇲' },
    { code: '+1', name: 'Canada', flag: '🇨🇦' },
    { code: '+236', name: 'République centrafricaine', flag: '🇨🇫' },
    { code: '+235', name: 'Tchad', flag: '🇹🇩' },
    { code: '+56', name: 'Chili', flag: '🇨🇱' },
    { code: '+86', name: 'Chine', flag: '🇨🇳' },
    { code: '+57', name: 'Colombie', flag: '🇨🇴' },
    { code: '+269', name: 'Comores', flag: '🇰🇲' },
    { code: '+242', name: 'Congo', flag: '🇨🇬' },
    { code: '+506', name: 'Costa Rica', flag: '🇨🇷' },
    { code: '+385', name: 'Croatie', flag: '🇭🇷' },
    { code: '+53', name: 'Cuba', flag: '🇨🇺' },
    { code: '+357', name: 'Chypre', flag: '🇨🇾' },
    { code: '+420', name: 'République tchèque', flag: '🇨🇿' },
    { code: '+45', name: 'Danemark', flag: '🇩🇰' },
    { code: '+253', name: 'Djibouti', flag: '🇩🇯' },
    { code: '+1-767', name: 'Dominique', flag: '🇩🇲' },
    { code: '+1-809', name: 'République dominicaine', flag: '🇩🇴' },
    { code: '+670', name: 'Timor oriental', flag: '🇹🇱' },
    { code: '+593', name: 'Équateur', flag: '🇪🇨' },
    { code: '+20', name: 'Égypte', flag: '🇪🇬' },
    { code: '+503', name: 'Salvador', flag: '🇸🇻' },
    { code: '+240', name: 'Guinée équatoriale', flag: '🇬🇶' },
    { code: '+291', name: 'Érythrée', flag: '🇪🇷' },
    { code: '+372', name: 'Estonie', flag: '🇪🇪' },
    { code: '+268', name: 'Eswatini', flag: '🇸🇿' },
    { code: '+251', name: 'Éthiopie', flag: '🇪🇹' },
    { code: '+679', name: 'Fidji', flag: '🇫🇯' },
    { code: '+358', name: 'Finlande', flag: '🇫🇮' },
    { code: '+33', name: 'France', flag: '🇫🇷' },
    { code: '+241', name: 'Gabon', flag: '🇬🇦' },
    { code: '+220', name: 'Gambie', flag: '🇬🇲' },
    { code: '+995', name: 'Géorgie', flag: '🇬🇪' },
    { code: '+49', name: 'Allemagne', flag: '🇩🇪' },
    { code: '+233', name: 'Ghana', flag: '🇬🇭' },
    { code: '+30', name: 'Grèce', flag: '🇬🇷' },
    { code: '+1-473', name: 'Grenade', flag: '🇬🇩' },
    { code: '+502', name: 'Guatemala', flag: '🇬🇹' },
    { code: '+224', name: 'Guinée', flag: '🇬🇳' },
    { code: '+245', name: 'Guinée-Bissau', flag: '🇬🇼' },
    { code: '+592', name: 'Guyana', flag: '🇬🇾' },
    { code: '+509', name: 'Haïti', flag: '🇭🇹' },
    { code: '+504', name: 'Honduras', flag: '🇭🇳' },
    { code: '+36', name: 'Hongrie', flag: '🇭🇺' },
    { code: '+354', name: 'Islande', flag: '🇮🇸' },
    { code: '+91', name: 'Inde', flag: '🇮🇳' },
    { code: '+62', name: 'Indonésie', flag: '🇮🇩' },
    { code: '+98', name: 'Iran', flag: '🇮🇷' },
    { code: '+964', name: 'Irak', flag: '🇮🇶' },
    { code: '+353', name: 'Irlande', flag: '🇮🇪' },
    { code: '+972', name: 'Israël', flag: '🇮🇱' },
    { code: '+39', name: 'Italie', flag: '🇮🇹' },
    { code: '+225', name: "Côte d'Ivoire", flag: '🇨🇮' },
    { code: '+1-876', name: 'Jamaïque', flag: '🇯🇲' },
    { code: '+81', name: 'Japon', flag: '🇯🇵' },
    { code: '+962', name: 'Jordanie', flag: '🇯🇴' },
    { code: '+7', name: 'Kazakhstan', flag: '🇰🇿' },
    { code: '+254', name: 'Kenya', flag: '🇰🇪' },
    { code: '+686', name: 'Kiribati', flag: '🇰🇮' },
    { code: '+383', name: 'Kosovo', flag: '🇽🇰' },
    { code: '+965', name: 'Koweït', flag: '🇰🇼' },
    { code: '+996', name: 'Kirghizistan', flag: '🇰🇬' },
    { code: '+856', name: 'Laos', flag: '🇱🇦' },
    { code: '+371', name: 'Lettonie', flag: '🇱🇻' },
    { code: '+961', name: 'Liban', flag: '🇱🇧' },
    { code: '+266', name: 'Lesotho', flag: '🇱🇸' },
    { code: '+231', name: 'Libéria', flag: '🇱🇷' },
    { code: '+218', name: 'Libye', flag: '🇱🇾' },
    { code: '+423', name: 'Liechtenstein', flag: '🇱🇮' },
    { code: '+370', name: 'Lituanie', flag: '🇱🇹' },
    { code: '+352', name: 'Luxembourg', flag: '🇱🇺' },
    { code: '+261', name: 'Madagascar', flag: '🇲🇬' },
    { code: '+265', name: 'Malawi', flag: '🇲🇼' },
    { code: '+60', name: 'Malaisie', flag: '🇲🇾' },
    { code: '+960', name: 'Maldives', flag: '🇲🇻' },
    { code: '+223', name: 'Mali', flag: '🇲🇱' },
    { code: '+356', name: 'Malte', flag: '🇲🇹' },
    { code: '+692', name: 'Marshall', flag: '🇲🇭' },
    { code: '+222', name: 'Mauritanie', flag: '🇲🇷' },
    { code: '+230', name: 'Maurice', flag: '🇲🇺' },
    { code: '+52', name: 'Mexique', flag: '🇲🇽' },
    { code: '+691', name: 'Micronésie', flag: '🇫🇲' },
    { code: '+373', name: 'Moldavie', flag: '🇲🇩' },
    { code: '+377', name: 'Monaco', flag: '🇲🇨' },
    { code: '+976', name: 'Mongolie', flag: '🇲🇳' },
    { code: '+382', name: 'Monténégro', flag: '🇲🇪' },
    { code: '+212', name: 'Maroc', flag: '🇲🇦' },
    { code: '+258', name: 'Mozambique', flag: '🇲🇿' },
    { code: '+264', name: 'Namibie', flag: '🇳🇦' },
    { code: '+674', name: 'Nauru', flag: '🇳🇷' },
    { code: '+977', name: 'Népal', flag: '🇳🇵' },
    { code: '+64', name: 'Nouvelle-Zélande', flag: '🇳🇿' },
    { code: '+505', name: 'Nicaragua', flag: '🇳🇮' },
    { code: '+227', name: 'Niger', flag: '🇳🇪' },
    { code: '+234', name: 'Nigeria', flag: '🇳🇬' },
    { code: '+850', name: 'Corée du Nord', flag: '🇰🇵' },
    { code: '+389', name: 'Macédoine du Nord', flag: '🇲🇰' },
    { code: '+47', name: 'Norvège', flag: '🇳🇴' },
    { code: '+968', name: 'Oman', flag: '🇴🇲' },
    { code: '+92', name: 'Pakistan', flag: '🇵🇰' },
    { code: '+680', name: 'Palaos', flag: '🇵🇼' },
    { code: '+970', name: 'Palestine', flag: '🇵🇸' },
    { code: '+507', name: 'Panama', flag: '🇵🇦' },
    { code: '+675', name: 'Papouasie-Nouvelle-Guinée', flag: '🇵🇬' },
    { code: '+595', name: 'Paraguay', flag: '🇵🇾' },
    { code: '+51', name: 'Pérou', flag: '🇵🇪' },
    { code: '+63', name: 'Philippines', flag: '🇵🇭' },
    { code: '+48', name: 'Pologne', flag: '🇵🇱' },
    { code: '+351', name: 'Portugal', flag: '🇵🇹' },
    { code: '+974', name: 'Qatar', flag: '🇶🇦' },
    { code: '+40', name: 'Roumanie', flag: '🇷🇴' },
    { code: '+7', name: 'Russie', flag: '🇷🇺' },
    { code: '+250', name: 'Rwanda', flag: '🇷🇼' },
    { code: '+1-758', name: 'Sainte-Lucie', flag: '🇱🇨' },
    { code: '+503', name: 'Salvador', flag: '🇸🇻' },
    { code: '+685', name: 'Samoa', flag: '🇼🇸' },
    { code: '+378', name: 'Saint-Marin', flag: '🇸🇲' },
    { code: '+239', name: 'Sao Tomé-et-Principe', flag: '🇸🇹' },
    { code: '+966', name: 'Arabie saoudite', flag: '🇸🇦' },
    { code: '+221', name: 'Sénégal', flag: '🇸🇳' },
    { code: '+381', name: 'Serbie', flag: '🇷🇸' },
    { code: '+248', name: 'Seychelles', flag: '🇸🇨' },
    { code: '+232', name: 'Sierra Leone', flag: '🇸🇱' },
    { code: '+65', name: 'Singapour', flag: '🇸🇬' },
    { code: '+421', name: 'Slovaquie', flag: '🇸🇰' },
    { code: '+386', name: 'Slovénie', flag: '🇸🇮' },
    { code: '+677', name: 'Îles Salomon', flag: '🇸🇧' },
    { code: '+252', name: 'Somalie', flag: '🇸🇴' },
    { code: '+27', name: 'Afrique du Sud', flag: '🇿🇦' },
    { code: '+82', name: 'Corée du Sud', flag: '🇰🇷' },
    { code: '+211', name: 'Soudan du Sud', flag: '🇸🇸' },
    { code: '+34', name: 'Espagne', flag: '🇪🇸' },
    { code: '+94', name: 'Sri Lanka', flag: '🇱🇰' },
    { code: '+249', name: 'Soudan', flag: '🇸🇩' },
    { code: '+597', name: 'Suriname', flag: '🇸🇷' },
    { code: '+268', name: 'Eswatini', flag: '🇸🇿' },
    { code: '+46', name: 'Suède', flag: '🇸🇪' },
    { code: '+41', name: 'Suisse', flag: '🇨🇭' },
    { code: '+963', name: 'Syrie', flag: '🇸🇾' },
    { code: '+886', name: 'Taïwan', flag: '🇹🇼' },
    { code: '+992', name: 'Tadjikistan', flag: '🇹🇯' },
    { code: '+255', name: 'Tanzanie', flag: '🇹🇿' },
    { code: '+66', name: 'Thaïlande', flag: '🇹🇭' },
    { code: '+228', name: 'Togo', flag: '🇹🇬' },
    { code: '+676', name: 'Tonga', flag: '🇹🇴' },
    { code: '+1-868', name: 'Trinité-et-Tobago', flag: '🇹🇹' },
    { code: '+216', name: 'Tunisie', flag: '🇹🇳' },
    { code: '+90', name: 'Turquie', flag: '🇹🇷' },
    { code: '+688', name: 'Tuvalu', flag: '🇹🇻' },
    { code: '+256', name: 'Ouganda', flag: '🇺🇬' },
    { code: '+380', name: 'Ukraine', flag: '🇺🇦' },
    { code: '+971', name: 'Émirats arabes unis', flag: '🇦🇪' },
    { code: '+598', name: 'Uruguay', flag: '🇺🇾' },
    { code: '+998', name: 'Ouzbékistan', flag: '🇺🇿' },
    { code: '+58', name: 'Venezuela', flag: '🇻🇪' },
    { code: '+84', name: 'Viêt Nam', flag: '🇻🇳' },
    { code: '+681', name: 'Wallis-et-Futuna', flag: '🇼🇫' },
    { code: '+967', name: 'Yémen', flag: '🇾🇪' },
    { code: '+260', name: 'Zambie', flag: '🇿🇲' },
    { code: '+263', name: 'Zimbabwe', flag: '🇿🇼' }
  ];
  